{% set name = "libhiredis" %}
{% set version = "1.4.0" %}
{% set soversion = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/redis/hiredis/archive/v{{ version }}.tar.gz
  sha256: 5fa6e719e59cd4f8ae435c52a18ac4035d135251f9ee54e7a045bccf59107ed8
  patches:
    - hiredis-1.1.0-disable-network-tests.patch

build:
  number: 0
  skip: true  # [win and int(float(vc)) < 14]
  run_exports:
    - {{ pin_subpackage('libhiredis', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

  host:
    - msinttypes  # [win and int(float(vc)) < 14]

test:
  commands:
    - ldd ${PREFIX}/lib/libhiredis.so  # [linux]
    - test -f ${PREFIX}/include/hiredis/hiredis.h  # [unix]
    - test -f ${PREFIX}/lib/libhiredis.{{ soversion }}${SHLIB_EXT}  # [osx]
    - if not exist %PREFIX%\\Library\\include\\hiredis\\hiredis.h exit 1  # [win]
    - echo "TODO - Pkg tests require redis server."

about:
  home: http://github.com/redis/hiredis
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Minimalistic C client for Redis >= 1.2

  dev_url: https://github.com/redis/hiredis

extra:
  recipe-maintainers:
    - apmorton
    - sarnold
